project_id = "lwbouxonjohqfdhnasvk"

[functions.bootstrap-admin]
verify_jwt = false

[functions.admin-create-user]
verify_jwt = false

[functions.ai-search-assistant]
verify_jwt = true

[functions.ai-chatbot]
verify_jwt = true

[functions.ai-analytics]
verify_jwt = true

[functions.ai-predictions]
verify_jwt = true

[functions.ai-smart-actions]
verify_jwt = true