project_id = "lwbouxonjohqfdhnasvk"

[functions.first-access]
verify_jwt = false

[functions.admin-create-user]
verify_jwt = true

[functions.ai-search-assistant]
verify_jwt = true

[functions.ai-chatbot]
verify_jwt = true

[functions.ai-analytics]
verify_jwt = true

[functions.ai-predictions]
verify_jwt = true

[functions.ai-smart-actions]
verify_jwt = true

[functions.check-leaked-passwords]
verify_jwt = true

[functions.ai-analytics-stream]
verify_jwt = true

[functions.seed-apple-models]
verify_jwt = true

[functions.inventory-import]
verify_jwt = true