// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lwbouxonjohqfdhnasvk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx3Ym91eG9uam9ocWZkaG5hc3ZrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc2MjIxMzcsImV4cCI6MjA3MzE5ODEzN30.mrXXfVX5FR1wLpYjya92HDVwzTM3aOFSqscqYE4pIDo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});